name: Python Script Workflow

on:
  push:
    branches:
      - master  # 每当提交推送到 master 分支时执行
  pull_request:
    branches:
      - master  # 提交 PR 时触发执行

jobs:
  run:
    runs-on: ubuntu-latest  # GitHub Actions 使用的操作系统

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # 拉取代码库

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'  # 设置 Python 版本（可以根据需要更改）

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt  # 安装项目依赖

    - name: Run the script
      run: |
        python test.py  # 执行你的 Python 脚本

    - name: Commit and push Subscription.yaml to repository
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add Subscription.yaml  # 添加文件到暂存区
        git commit -m "Add Subscription.yaml"  # 提交文件
        git push origin master  # 将文件推送到 master 分支
