name: Python Script Workflow

on:
  push:
    branches:
      - master  # 每当提交推送到 master 分支时执行
  pull_request:
    branches:
      - master  # 提交 PR 时触发执行
  schedule:
    # 定义每6小时自动运行一次任务
    - cron: '0 */6 * * *'  # 这表示每6小时执行一次任务

jobs:
  run:
    runs-on: ubuntu-latest  # GitHub Actions 使用的操作系统

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # 拉取代码库

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'  # 设置 Python 版本（可以根据需要更改）

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt  # 安装项目依赖

    - name: Run the script
      run: |
        python main.py  # 执行你的 Python 脚本

    - name: Commit Subscription.yaml to repository
      run: |
        # Check if the Subscription.yaml exists
        if [ -f "Subscription.yaml" ]; then
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add Subscription.yaml
          git commit -m "Add Subscription.yaml"
          git push
        else
          echo "No Subscription.yaml found to commit."
        fi
